### PR TITLE
Fix error with heredoc closing label thingy

### PR DESCRIPTION
**Pull request by BenSandeen**
When testing out https://github.com/DripEmail/drip/pull/23679, I spent an hour trying to figure out how to get the cURL command shown here to work: https://developer.drip.com/?shell#batch-api

I finally tried removing the indentation in front of the closing `EOF`, and the request went through.  Not the sort of experience we want to give our customers.

With the indentation:
```bash
$ curl -v -X POST "https://api-staging.getdrip.com/v2/7435085/subscribers/batches.json" \
  -H "Content-Type: application/json" \
  -H "User-Agent: http://test.grange.io/" \
  -u b41fade82d4b47fa127001d934544287: \
  -d @- << EOF
        {
    "batches": [{
      "subscribers": [
        {
          "email": "john-schmon@acme.com",
          "time_zone": "America/Los_Angeles",
          "tags": ["Customer", "SEO"],
          "custom_fields": {
            "shirt_size": "Medium"
          }
        },
        {
          "email": "joe@acme.com",
          "time_zone": "America/Los_Angeles",
          "tags": ["Prospect"],
          "custom_fields": {
            "shirt_size": "Medium"
          }
        }
      ]
    }]
  }
  EOF
heredoc> # I had to hit CTRL+c here to kill it
$ 
```
Without the indentation (apparently even github's markdown recognizes the difference; notice the color of the closing `EOF`):
```bash
$ curl -v -X POST "https://api-staging.getdrip.com/v2/7435085/subscribers/batches.json" \
  -H "Content-Type: application/json" \
  -H "User-Agent: http://test.grange.io/" \
  -u b41fade82d4b47fa127001d934544287: \
  -d @- << EOF
        {
    "batches": [{
      "subscribers": [
        {
          "email": "john-schmon@acme.com",
          "time_zone": "America/Los_Angeles",
          "tags": ["Customer", "SEO"],
          "custom_fields": {
            "shirt_size": "Medium"
          }
        },
        {
          "email": "joe@acme.com",
          "time_zone": "America/Los_Angeles",
          "tags": ["Prospect"],
          "custom_fields": {
            "shirt_size": "Medium"
          }
        }
      ]
    }]
  }
EOF
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 54.192.58.60:443...
* Connected to api-staging.getdrip.com (54.192.58.60) port 443 (#0)

[...omitting about 100 lines of output...]

* Connection #0 to host api-staging.getdrip.com left intact
{"message":"API rate limit exceeded. Please try again in an hour."}% # This response is expected, since I had already finished testing the rate limiting was working before grabbing this output
$ 
```

### CODE REVIEW

**Review by will-in-wi — APPROVED** [review]

**Review by xdlbx — APPROVED** [review]

**Review by timbreitkreutz — APPROVED** [review]
Thanks for fixing this Ben!

**Review by tamouse — APPROVED** [review]
Great catch!!

Shells don't allow the indenting of the EOF, i.e. the closing string for the heredoc.

I'm willing to be it was copy-pasted from a ruby example

**Comment by BenSandeen** [comment]
Since it looks like we've got a bunch of approvals for this, how do I deploy it?

**Comment by jeremyhaberman** [comment]
> Since it looks like we've got a bunch of approvals for this, how do I deploy it?

I don't remember what I did, but I do remember consulting the README of the api-docs repo, and I don't remember having any issues. I think you just run `script/release`.

Holler at me in Slack if you have any questions or want to pair on it.

**Pull request merged**
